source 'https://github.com/CocoaPods/Specs.git'
#source "git@gitlab.alibaba-inc.com:alipods/specs.git"
#source "git@gitlab.alibaba-inc.com:alipods/specs-mirror.git"

target "CPDataDrivenLayout iOS Example" do
	platform :ios, '7.0'
	pod 'CPDataDrivenLayout', :path => '../..'
	pod 'UITableView+FDTemplateLayoutCell', :git => 'https://github.com/forkingdog/UITableView-FDTemplateLayoutCell.git', :tag => '1.6'
end
